//
//  SwiftFileGenerator.swift
//  Bian
//
//  Created by Ashley Cameron on 27/07/2020.
//

import Foundation

struct SwiftFileGenerator {

	static func createIconsEnum(url: URL, iconNames: [String]) throws {
		var swiftString = "//\n// Autogenerated file, changes will be overwritten.\n//"
		swiftString += "\n\nenum AlternativeAppIcon: String, CaseIterable {\n"
		iconNames.forEach { swiftString += "\tcase \($0)\n"}
		swiftString += "}\n"

		guard let data = swiftString.data(using: .utf8) else {
			throw BianError.failedToGenerateOutputSwiftFile
		}
		try data.write(to: url)
	}
}
